title: O. Michael Adesanya
logo: 
show_downloads: true
theme: Jekyll-theme-minimal

title_image: /assets/img/title-image.png
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:

<header>
        <a href="{{ site.github.url }}"> <h1>{{ site.title | default: site.github.repository_name }}</h1> </a>

	{% if site.title_image %}
	  <img src="{{site.title_image}}" alt="Title image"></img>
	{% if site.logo %}
	  <img src="{{site.logo}}" alt="Logo"></img>
